import { StyleSheet } from "react-native";

export const style = StyleSheet.create({
    background: {
        flex: 1,
        width: "100%",
        height: "100%",
    },
    container: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 30,
    },
    headerContainer: {
        width: "100%",
        alignItems: "center",
        marginBottom: 40,
    },
    title: {
        color: "#FFFFFF",
        fontSize: 26,
        fontWeight: "bold",
        textTransform: "uppercase",
        textAlign: "center",
        textShadowColor: "#000000",
        textShadowOffset: { width: 4, height: 2 },
        textShadowRadius: 3,
        paddingVertical: 8,
        paddingHorizontal: 12,
        backgroundColor: "rgba(0, 0, 0, 0.4)",
    },
    form: {
        width: "100%",
        gap: 20,
        marginBottom: 50,
    },
    input: {
        borderWidth: 2,
        borderColor: "#D4AF37",
        borderRadius: 12,
        padding: 12,
        backgroundColor: "#ffffff",
        fontSize: 16,
        color: "#000",
    },
    button: {
        width: "100%",
        backgroundColor: "#D4AF37",
        paddingVertical: 14,
        borderRadius: 14,
        alignItems: "center",
        borderWidth: 3,
        borderColor: "#000000",
    },
    buttonText: {
        color: "#000000",
        fontSize: 18,
        fontWeight: "bold",
        textTransform: "uppercase",
    },
    footer: {
        alignItems: "center",
        width: "100%",
        marginTop: 20,
    },
    textBottom: {
        color: "#FFFFFF",
        fontSize: 14,
        marginTop: 10,
        textShadowColor: "#000000",
        textShadowOffset: { width: 2, height: 1 },
        textShadowRadius: 2,
    },
    textLink: {
        color: "#D4AF37",
        fontWeight: "bold",
        textDecorationLine: "underline",
    },
});
